enum RecipeCategory {
  APPETIZERS = "aperitivos",
  ASIAN = "asiática",
  SIDE_DISHES = "acompanhamentos",
  BBQ = "churrasco",
  STEAKHOUSE = "churrascaria",
  COMFORT_FOOD = "comida caseira",
  BREAKFAST = "café da manhã",
  BRUNCH = "brunch",
  BRAZILIAN = "brasileira",
  BAKERY = "padaria",
  BURGER = "hambúrguer",
  DAIRY_FREE = "sem lactose",
  DESSERT = "sobremesa",
  DRINKS = "bebidas",
  FUSION = "fusão",
  GLUTEN_FREE = "sem glúten",
  HEALTHY = "saudável",
  ICE_CREAM = "sorvete",
  ITALIAN = "italiana",
  MEXICAN = "mexicana",
  PASTA = "massa",
  PIZZA = "pizza",
  SALAD = "salada",
  SANDWICHES = "sanduíche",
  SEAFOOD = "frutos do mar",
  SOUP = "sopa",
  SUSHI = "sushi",
  TAPAS = "tapas",
  VEGAN = "vegana",
  VEGETARIAN = "vegetariana",
}

export default RecipeCategory;
