enum RecipeCategory {
  PIZZA = 'pizza',
  BURGER = 'hambúrguer',
  ITALIAN = 'italiana',
  SUSHI = 'sushi',
  DESSERT = 'sobremesa',
  SALAD = 'salada',
  PASTA = 'massa',
  SEAFOOD = 'frutos do mar',
  STEAKHOUSE = 'churrascaria',
  MEXICAN = 'mexicana',
  ASIAN = 'asiática',
  BRAZILIAN = 'brasileira',
  VEGETARIAN = 'vegetariana',
  VEGAN = 'vegana',
  BAKERY = 'padaria',
  DRINKS = 'bebidas',
  ICE_CREAM = 'sorvete',
  SOUP = 'sopa',
  BBQ = 'churrasco',
  SANDWICHES = 'sanduíche',
  TAPAS = 'tapas',
  FUSION = 'fusão',
  HEALTHY = 'saudável',
  COMFORT_FOOD = 'comida caseira',
  BREAKFAST = 'café da manhã',
  BRUNCH = 'brunch',
  APPETIZERS = 'aperitivos',
  SIDE_DISHES = 'acompanhamentos',
  GLUTEN_FREE = 'sem glúten',
  DAIRY_FREE = 'sem lactose',
}

export default RecipeCategory;